# Liste

In [7]:
liste = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

In [8]:
for l in liste: 
    print(l)

1
2
3
4
5
6
7
8
9
10


In [9]:
print("number of elements in the list: ", len(liste))

number of elements in the list:  10


In [10]:
liste.append(19876)

In [11]:
liste

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 19876]

In [12]:
liste.append("azze")

In [13]:
liste

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 19876, 'azze']

In [14]:
myList = ["Python", "Java", "NodeJS"]

In [15]:

#Insérer un élément en deuxième position:
myList = ["Python", "Java", "PHP"]
myList.insert(1 , "NodeJS")
print(myList)

['Python', 'NodeJS', 'Java', 'PHP']


In [16]:

#suppression d'un élément spécifié avec la méthode remove()
myList = ["Python", "C++", "PHP"]
myList.remove("C++")
print(myList)

['Python', 'PHP']


# 7. Liste en compréhension

In [17]:
liste_even = [ 2*n for n in range(5) ]
liste_even

[0, 2, 4, 6, 8]

In [18]:
liste_even_mult_3 = [2*n for n in range(10) if n%3==0]
liste_even_mult_3

[0, 6, 12, 18]

# Découpage d'une liste ( list slicing)

In [23]:
# découpage depuis  l'index 3 jusqu'au index 6
my_list = ['h','e','l','l','o','w','o','r','l', 'd']

In [22]:
my_list[3:6]

['l', 'o', 'w']

In [28]:
# extraction du dernier élément
print(my_list[-1])

d


In [29]:
print(my_list[-4])

o


# A propos de la fonction lumbda

In [30]:
y = lambda x: x+x

In [31]:
print(y)

<function <lambda> at 0x123b949a0>


In [32]:
y(10)

20

In [33]:
L = [1, 2, 3, 4, 5]

In [37]:
lis = list(map( lambda x:x**x , L ))

In [38]:
print(lis)

[1, 4, 27, 256, 3125]


# Programmation Orientée Objet

In [59]:
class Vehicule:
    def __init__(self , marque , couleur):
        self.marque = marque
        self.couleur = couleur
        print("je sus un vehicule")
        
    
    def demarrer(self):
        print(f" {self.marque} {self.couleur} a démarrer")
    
    

In [41]:
T = Vehicule("Toyota", "Rouge")

In [42]:
T.demarrer()

 Toyota Rouge a démarrer


# 'Héritage

In [60]:
class moto (Vehicule):
    
   def __init__(self, marque, couleur):
        super().__init__(marque, couleur)
        print("je suis une moto")

In [61]:
m = moto("SH","Bleu")


je sus un vehicule
je suis une moto


In [65]:
class Point2D:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y

    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Point2D(x, y)

    def __repr__(self):
        return f' dans repr(x={self.x}, y={self.y})'

    def __str__(self):
        return f'dans str ({self.x}, {self.y})'

a = Point2D(1, 2)

In [66]:

print(a) # appel à __str__() implicitement

print(a.__str__())
print(str(a)) # méthode __str__() mais plus propre

dans str (1, 2)
dans str (1, 2)
dans str (1, 2)


In [67]:

print(a.__repr__())
print(repr(a)) # méthode __repr__() mais plus propre

 dans repr(x=1, y=2)
 dans repr(x=1, y=2)


# Les Fichiers

In [80]:
# créer un fichier pour le lire ensuite
! echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum mauris in metus rutrum, pharetra imperdiet purus auctor." > file.txt
! echo "Fusce ac luctus massa. Integer dapibus eu sapien at venenatis. Phasellus vel aliquet ante." >> file.txt
! echo "Integer consectetur efficitur commodo. Quisque dignissim ultrices placerat." >> file.txt

In [81]:
f = open("file.txt", "r")
print(f.read())
f.close()

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum mauris in metus rutrum, pharetra imperdiet purus auctor.
Fusce ac luctus massa. Integer dapibus eu sapien at venenatis. Phasellus vel aliquet ante.
Integer consectetur efficitur commodo. Quisque dignissim ultrices placerat.



In [82]:
with open("file.txt" , "r") as mon_fichier:
    lignes = mon_fichier.readlines()
    print(lignes)
    print("\n")
    print(" of ligne : " , len(lignes))

['Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum mauris in metus rutrum, pharetra imperdiet purus auctor.\n', 'Fusce ac luctus massa. Integer dapibus eu sapien at venenatis. Phasellus vel aliquet ante.\n', 'Integer consectetur efficitur commodo. Quisque dignissim ultrices placerat.\n']


 of ligne :  3


In [75]:
with open("file.txt" , "r") as mon_fichier:
    for ligne in mon_fichier:
        print(ligne)

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum mauris in metus rutrum, pharetra imperdiet purus auctor.

Fusce ac luctus massa. Integer dapibus eu sapien at venenatis. Phasellus vel aliquet ante.

Integer consectetur efficitur commodo. Quisque dignissim ultrices placerat.



In [83]:
with open("file.txt" , 'a') as mon_fichier:
    mon_fichier.write("Diamou Serigne Touba\n")
    mon_fichier.write("Diamou Serigne Touba\n")

In [84]:
with open("file.txt" , "r") as mon_fichier:
    for ligne in mon_fichier:
        print(ligne)

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum mauris in metus rutrum, pharetra imperdiet purus auctor.

Fusce ac luctus massa. Integer dapibus eu sapien at venenatis. Phasellus vel aliquet ante.

Integer consectetur efficitur commodo. Quisque dignissim ultrices placerat.

Diamou Serigne Touba

Diamou Serigne Touba



# Exceptions

In [ ]:
x = -1

try:
    if x < 0:
        raise Exception("Sorry, no numbers below zero")
except:
    print("Something went wrong ++")
else:
    print("Nothing went wrong -- ")
finally:
    print("Something or Nothing went wrong")

# Numpy

In [85]:
import numpy as np

tab = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [96]:
tab.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [86]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

In [87]:
b.shape

(2, 3)

In [88]:
b.ndim

2

In [89]:
b.size

6

In [90]:
a = np.array([1, 2, 3])

b = np.array([[1, 2, 3],
              [4, 5, 6]])

c = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])

print('La forme de a est:', a.shape)
print('Le nombre de dimensions de a est:', a.ndim)
print('Le nombre total d\'éléments dans a est:', a.size)
print()
print('La forme de b est:', b.shape)
print('Le nombre de dimensions de b est:', b.ndim)
print('Le nombre total d\'éléments dans b est:', b.size)
print()
print('La forme de c est:', c.shape)
print('Le nombre de dimensions de c est:', c.ndim)
print('Le nombre total d\'éléments dans c est:', c.size)


La forme de a est: (3,)
Le nombre de dimensions de a est: 1
Le nombre total d'éléments dans a est: 3

La forme de b est: (2, 3)
Le nombre de dimensions de b est: 2
Le nombre total d'éléments dans b est: 6

La forme de c est: (2, 2, 2)
Le nombre de dimensions de c est: 3
Le nombre total d'éléments dans c est: 8


In [92]:
data = np.arange(6)
print(data, "\n")
data = data.reshape(2, 3)
print(data , "\n")
data = data.reshape(3, 2)
print(data , "\n")

[0 1 2 3 4 5] 

[[0 1 2]
 [3 4 5]] 

[[0 1]
 [2 3]
 [4 5]] 



In [93]:
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [94]:
data.reshape(3, -1)

array([[0, 1],
       [2, 3],
       [4, 5]])